audio:
  bgm: true
  bgm_db: -15
  limit: 18
  main_db: 15
  rate: +30%
  role: zh-CN-YunxiNeural
  volume: +100%
chatgpt:
  ForwardKey: ollama
  max_token: 16385
  model: gemma2
  url: http://127.0.0.1:11434/api
potential:
  max_length: 4
  max_words: 40
  min_length: 2
  min_words: 30
  top_n: 1
source_path: G:\novelTVFile
stable_diffusion:
  server_ip: http://127.0.0.1:7860
video:
  animation: true
  animation_speed: 1.2
  fontcolor: FFFFFF
  font: ./assets/font/simhei.ttf
  fontsize: 12
  imagemagick_path: D:\Work\ImageMagick\magick.exe
  kerning: 1
  position: 2
  stroke_color: yellow
  stroke_width: 1.2
  subtitles: true
  use_moviepy: false
